""" ASS enumerations """

ASS_HINTING_NONE = 0x0
ASS_HINTING_LIGHT = 0x1
ASS_HINTING_NORMAL = 0x2
ASS_HINTING_NATIVE = 0x3
ASS_SHAPING_SIMPLE = 0x0
ASS_SHAPING_COMPLEX = 0x1
ASS_OVERRIDE_DEFAULT = 0x0
ASS_OVERRIDE_BIT_STYLE = 0x1
ASS_OVERRIDE_BIT_SELECTIVE_FONT_SCALE = 0x2
ASS_OVERRIDE_BIT_FONT_SIZE = 0x2
ASS_OVERRIDE_BIT_FONT_SIZE_FIELDS = 0x4
ASS_OVERRIDE_BIT_FONT_NAME = 0x8
ASS_OVERRIDE_BIT_COLORS = 0x10
ASS_OVERRIDE_BIT_ATTRIBUTES = 0x20
ASS_OVERRIDE_BIT_BORDER = 0x40
ASS_OVERRIDE_BIT_ALIGNMENT = 0x80
ASS_OVERRIDE_BIT_MARGINS = 0x100
ASS_OVERRIDE_FULL_STYLE = 0x200
ASS_OVERRIDE_BIT_JUSTIFY = 0x400
ASS_FONTPROVIDER_NONE = 0x0
ASS_FONTPROVIDER_AUTODETECT = 0x1
ASS_FONTPROVIDER_CORETEXT = 0x2
ASS_FONTPROVIDER_FONTCONFIG = 0x3
ASS_FONTPROVIDER_DIRECTWRITE = 0x5

""" YCbCrMatrix """

YCBCR_DEFAULT = 0x0
YCBCR_UNKNOWN = 0x1
YCBCR_NONE = 0x2
YCBCR_BT601_TV = 0x3
YCBCR_BT601_PC = 0x4
YCBCR_BT709_TV = 0x5
YCBCR_BT709_PC = 0x6
YCBCR_SMPTE240M_TV = 0x7
YCBCR_SMPTE240M_PC = 0x8
YCBCR_FCC_TV = 0x9
YCBCR_FCC_PC = 0xA

""" Private Enum """

IMAGE_TYPE_CHARACTER = 0x0
IMAGE_TYPE_OUTLINE = 0x1
IMAGE_TYPE_SHADOW = 0x2
TRACK_TYPE_UNKNOWN = 0x0
TRACK_TYPE_ASS = 0x1
TRACK_TYPE_SSA = 0x2
